### ISSUE TITLE
Getting dimension mismatch on running YoloV5s model

### ISSUE THREAD

**Issue by manish0079** [niqbal996/triton_client_yolo#1]
Box array shape : (1, 3, 40, 85)

> Traceback (most recent call last):
>   File "main.py", line 172, in <module>
>     predictions.append(extract_boxes_triton(response, result_filenames[idx], FLAGS.batch_size))
>   File "/triton_client_yolo/utils/postprocess.py", line 94, in extract_boxes_triton
>     l_box_array = box_array[i, argwhere, :]
> IndexError: too many indices for array: array is 4-dimensional, but 5 were indexed

**Comment by niqbal996** [comment]
Hi @manish0079, 
At the moment, the client is not very generic to be able to process all kinds of different dimensions of the box array. For a proof of concept, i gave a refence config.pbtxt file [here](https://github.com/niqbal996/triton_client_yolo/blob/main/examples/config.pbtxt) I used for the model exported via `pytorch2onnx.py` file. Here the box array returned is of size `dims: [1, 16128, 1, 4]` as shown in the config file. I used the input image size `512 x 512` which also changes the number of boxes produced. If you are using a different model, which is YOLOv5s in this case, you will have to adjust the dimensions to your case. 
Also try using a model of batch size 1, since batched input is not supported at the moment.
